apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::791924433642:role/eksctl-eksctl-demo-nodegroup-ng-16-NodeInstanceRole-aKg0gnglYGHX
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::791924433642:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-12T12:57:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1182"
  uid: 19c0123e-9509-493a-8104-5cc41c88e5f6
