apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::791924433642:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-FeC4ih3vyBqT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
        rolearn: arn:aws:iam::791924433642:role/UdacityFlaskDeployCBKubectlRole
        username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-07T15:43:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1771"
  uid: 413cb63a-b3a1-4724-973c-9165afee14c3
